apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gke-cicd-p6
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: gke-cicd-p6.local
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gke-cicd-p6
            port:
              number: 80