apiVersion: v1
kind: Service
metadata:
  name: gke-cicd-p6
  labels:
    app: gke-cicd-p6
spec:
  selector:
    app: gke-cicd-p6
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080